Implement Fastest CP module
evoesports/EvoSC-sharp pull request #122
Opened 2023-02-19 14:00 UTC by kdankert

Started to work a bit on this as an introduction to this project. Already worked a bit with the old version written in PHP and would like to help in this rewrite. 

I based this branch on the manialink branch, as I think, those features will be needed for the widget itself, though as far as I figured out the template engine is not quite ready yet. 

Tests are still missing, but I couldn't figure out the guidelines for tests inside modules, as no module has tests so far. 

In addition to that I still need to verify, that the state of the service is actually thread-safe, as events are most likely to be handled on multiple threads or am I mistaken. 

I thought it would make sense to create a draft pull request though, to let you know that this module is being worked on and to get some early feedback. 

Closes #27.

2023-02-20 07:07 UTC, snixtho commented
Hwy, thanks for helping out! If you'd like, I can add you to the development channel in discord where we are discussing and collaborating on the development of EvoSC#. I think you made a ticket to help out at some point, but was never added to the channel? I can help you get sorted out if you contact me on discord: snixtho#9039

2023-04-15 11:05 UTC, kdankert commented
This PR requires #128 to be merged before (target branch needs to be adjusted after).
The last commit splitting the manialink manager interface can either be done in #122 or #128.

2023-04-17 06:35 UTC, AtomicLiquid approved these changes

2023-06-02 07:05 UTC, snixtho requested changes
Nice work! I added some comments and suggestions for you.

2023-06-02 07:05 UTC, snixtho commented on tests/Modules/FastestCp.Tests/FastestCpControllerTest.cs
> +    public async void ShouldRegisterTimeAndShowWidget()
```suggestion
    public async void Should_Register_Time_And_Show_Widget()
```

To keep consistency, we should stick with snake case.

2023-06-02 07:05 UTC, snixtho commented on tests/Modules/FastestCp.Tests/FastestCpControllerTest.cs
> +    public async void ShouldResetStore()
```suggestion
    public async void Should_Reset_Store()

```

2023-06-02 07:05 UTC, snixtho commented on tests/Modules/FastestCp.Tests/FastestCpManialinkTest.cs
> +    public async void ShouldRenderEmptyWidget()
```suggestion
    public async void Should_Render_Empty_Widget()
```

2023-06-02 07:05 UTC, snixtho commented on tests/Modules/FastestCp.Tests/FastestCpManialinkTest.cs
> +    public async void ShouldRenderFilledWidget()
```suggestion
    public async void Should_Render_Filled_Widget()
```

2023-06-02 07:05 UTC, snixtho commented on tests/Modules/FastestCp.Tests/FastestCpServiceTest.cs
> +    public async void ShouldRegisterTimeAndShowWidget()
```suggestion
    public async void Should_Register_Time_And_Show_Widget()
```

2023-06-02 07:05 UTC, snixtho commented on tests/Modules/FastestCp.Tests/FastestCpServiceTest.cs
> +    public async void ShouldRegisterTimeSlowerTimeAndNotShowWidget()
```suggestion
    public async void Should_Register_Time_Slower_Time_And_Not_Show_Widget()
```

2023-06-02 07:05 UTC, snixtho commented on tests/Modules/FastestCp.Tests/FastestCpServiceTest.cs
> +    public async void ShouldResetStore()
```suggestion
    public async void Should_Reset_Store()
```

2023-06-03 13:25 UTC, snixtho approved these changes
Looks good to me. But it seems like the build and Sonarcloud is failing for not finding the ManiaTemplates project?

2023-06-03 13:57 UTC, kdankert commented
Saw that, but couldn't figure out yet, what the problem is. First guess was, that this might be a caching issue, but I'll investigate further.

2023-06-04 11:42 UTC, AtomicLiquid approved these changes

2023-06-04 11:42 UTC, AtomicLiquid commented on src/Modules/FastestCp/Services/FastestCpService.cs
> +        _logger.LogDebug("Hide fastest cp manialink for all users");
```suggestion
        _logger.LogDebug("Hiding fastest cp manialink for all users");
```

2023-06-04 11:42 UTC, AtomicLiquid commented on src/Modules/FastestCp/Services/FastestCpService.cs
> +        _logger.LogDebug("Update fastest cp manialink for all users");
```suggestion
        _logger.LogDebug("Updating fastest cp manialink for all users");
```

2023-06-05 11:43 UTC, merged