UI Localization
evoesports/EvoSC-sharp pull request #166
Opened 2023-06-22 06:35 UTC by snixtho

- Adds a way for modules to register localization to be used anywhere.
- Can adapt to a player's own selected language.
- Ability to use indexer and dynamic object accessors, depending on the situation that fits best. (Dynamic is useful for Manialinks)
- Can translate locale names within arbitrary strings. Useful for setting up localization for compile-time constants such as command descriptions.

2023-06-23 11:06 UTC, AtomicLiquid requested changes

2023-06-23 13:52 UTC, snixtho commented on src/Modules/MapsModule/Controllers/MapsController.cs
> +        await _server.SuccessMessageAsync(_locale.PlayerLanguage.MapRemovedSuccessfully(mapId), Context.Player);
Can you elaborate?

2023-06-24 19:07 UTC, AtomicLiquid commented on src/Modules/MapsModule/Controllers/MapsController.cs
> +        await _server.SuccessMessageAsync(_locale.PlayerLanguage.MapRemovedSuccessfully(mapId), Context.Player);
![image](https://github.com/evoesports/EvoSC-sharp/assets/20260739/c4d0acc6-ee2c-42a5-aec9-d966955b5290)
MapAddedSuccessfully and MapRemovedSuccessfully should have the same structure.

2023-06-25 10:14 UTC, kdankert reviewed
Looks fine for me. We should definitely find a better way to mock contexts inside controllers. Also it would be great if test coverage could be improved. We should also integration test migrations to ensure they are working together (unit tests do not cover cases that might appear).

2023-06-25 11:26 UTC, snixtho commented
> Looks fine for me. We should definitely find a better way to mock contexts inside controllers. Also it would be great if test coverage could be improved. We should also integration test migrations to ensure they are working together (unit tests do not cover cases that might appear).

I agree, the tests in this PR are mostly only for what was actually added. There are a bunch of services and things in the core that needs tests, which we should create soon. I could make some issues on that.

2023-06-26 19:01 UTC, AtomicLiquid approved these changes

2023-06-27 06:33 UTC, merged