Merge XPEvo fixed/changes into main repository
EvoEsports/EvoSC-sharp pull request #317
Opened 2024-10-22 14:12 UTC by Chris92de

This pull request includes all the changes that were made to the XPEvo branch of EvoSC#, without the additions of ContactAdminModule, ToornamentModule and ServerSyncModule.
Changes to the required dependencies (namely NATS and toornamentapi) have been reverted.

New modules: RoundRankingModule
Updated modules: ScoreboardModule, GameModeUiModule

Full list of changes compared to `master` branch can be seen here: https://github.com/EvoEsports/EvoSC-sharp/compare/master...EvoEsports:EvoSC-sharp-XPEvo:master - keep in mind that some of these changes already have been merged into `master` branch here and were merged into the forked repository after the fact.

Abbreviated list of changes since August 20th:
- Updated design for `CurrentMapModule` by @araszka 
- Updated design and functionality for `SpectatorTargetInfoModule` by @araszka 
- Added `SpectatorCamModeModule` by @araszka - replaces Nadeo's default Spec Cam Mode switcher in the bottom right
- Rename `Scoreboard` to `ScoreboardModule`
- Updated design and functionality for `ScoreboardModule` (incl. themability, nickname support, showing current/max rounds, etc)
- Added `RoundRankingModule` by @araszka - similar functionality as SmallScoresTable in TMWT/Teams_Matchmaking modes
- Added default settings to `GameModeUiModule` for `SmallScoresTable` UILayer
- Few changes to the `Dockerfile` to make sure EvoSC runs as user id `9999` instead of root.

2024-10-27 15:42 UTC, araszka approved these changes

2024-10-27 21:30 UTC, Chris92de commented on docker/docker-compose.yml
> +    image: evoesports/evosc-sharp:latest
Oh I thought this was meant to be an example file for the public, hence why I worded the README.md file the way I did.

2024-11-02 20:12 UTC, snixtho commented
Because commit history seems to be lost, please create a list of changes in the description.

2024-11-05 06:58 UTC, Chris92de commented
> Because commit history seems to be lost, please create a list of changes in the description.

As requested, I've updated the description of the pull request with an abbreviated list of changes and also added a link to compare the fork to the current master branch.

2024-11-05 07:24 UTC, Chris92de commented on docker/docker-compose.yml
> +    image: evoesports/evosc-sharp:latest
This should now be fixed with the latest commit.

2024-11-05 07:25 UTC, Chris92de commented
The last commit resolves the comment by @AtomicLiquid about the `docker-compose.yml` file not including a build parameter.

2024-11-09 10:37 UTC, snixtho requested changes

2024-11-09 10:37 UTC, snixtho commented on src/Modules/RoundRankingModule/Services/RoundRankingService.cs
> +    public Task HideRoundRankingWidgetAsync() =>
This method does not belong in this service.

2024-11-09 10:37 UTC, snixtho commented on src/Modules/RoundRankingModule/Services/RoundRankingService.cs
> +public class RoundRankingService(
After looking at this entire class. I would split this up and only include necessary methods for updating/getting the state variables in this service. And then put methods that does some specialized operation on that data in a transient/scoped service. This way we don't have a do-it-all singleton that is references everywhere in memory and keep the single responsibility principle intact.

By doing this, it is way easier to manage the thread-safe operations on these variables as well.

2024-11-09 10:37 UTC, snixtho commented on src/Modules/RoundRankingModule/Templates/Components/RoundRankingRow.mt
> +                            text='{{ checkpoint.IsDNF ? Icons.FlagO : (checkpoint.IsFinish ? Icons.FlagCheckered : checkpoint.CheckpointId + 1) }}'
Maybe some sort of utility method would be better here than nesting ternary statements.

Actually would be nice if there the template engine had a way to define C# methods somewhere in the component that can be reused and make the code cleaner.

2024-11-09 10:37 UTC, snixtho commented on src/Modules/RoundRankingModule/Templates/Components/RoundRankingRow.mt
> +                        text="{{ checkpoint.IsDNF ? &quot;DNF&quot; : (checkpoint.TimeDifference!=null ? checkpoint.TimeDifference.ToString().TrimStart('0') : checkpoint.Time.ToString().TrimStart('0'
Maybe some sort of utility method would be better here than nesting ternary statements.

2024-11-09 10:37 UTC, snixtho commented on src/Modules/ScoreboardModule/Services/ScoreboardNicknamesService.cs
> +    private readonly Dictionary<string, string> _nicknames = new();
missing locks or change to ConcurrentDictionary

2024-11-09 10:37 UTC, snixtho commented on src/Modules/ScoreboardModule/Services/ScoreboardNicknamesService.cs
> +    public string ToManiaScriptArray(Dictionary<string, string> nicknameMap)
move out of class, this is an utility method

2024-11-09 10:37 UTC, snixtho commented on src/Modules/ScoreboardModule/Services/ScoreboardNicknamesService.cs
> +    public string ToManiaScriptArrayEntry(KeyValuePair<string, string> loginNickname)
utility method, move out of class

2024-11-09 10:37 UTC, snixtho commented on src/Modules/ScoreboardModule/Services/ScoreboardNicknamesService.cs
> +    public string EscapeNickname(string nickname)
utility method, move out of class

2024-11-09 10:37 UTC, snixtho commented on src/Modules/ScoreboardModule/Services/ScoreboardService.cs
> +    private bool _isWarmUp;
Suggestion on what you should do here:
- Move these state variables and related methods out of this class in it's own singleton service.
- Set this service as transient/scoped, depending on how its used.
- Inject the newly-created singleton into this class.

2024-11-09 10:37 UTC, snixtho commented on src/Modules/ScoreboardModule/Templates/Components/Body/Legend.mt
> +               pos="{{ positionBoxWidth/2.0 }} {{ height / -2 + 0.25 }}"
```suggestion
               pos="{{ positionBoxWidth/2f }} {{ height / -2 + 0.25 }}"
```

2024-11-09 10:37 UTC, snixtho commented on src/Modules/ScoreboardModule/Templates/Components/Body/Legend.mt
> +               pos="{{ positionBoxWidth+columnSpacing+(flagWidth/2.0) }} {{ height / -2 + 0.25 }}"
```suggestion
               pos="{{ positionBoxWidth+columnSpacing+(flagWidth/2f) }} {{ height / -2 + 0.25 }}"
```

2024-11-09 10:37 UTC, snixtho commented on src/Modules/ScoreboardModule/Templates/Components/Body/Legend.mt
> +               pos="{{ positionBoxWidth+columnSpacing+flagWidth+columnSpacing+(clubTagWidth/2.0) }} {{ height / -2 + 0.25 }}"
```suggestion
               pos="{{ positionBoxWidth+columnSpacing+flagWidth+columnSpacing+(clubTagWidth/2f) }} {{ height / -2 + 0.25 }}"
```

2024-11-09 10:37 UTC, snixtho commented on src/Modules/ScoreboardModule/Templates/Components/Body/Legend.mt
> +               pos="{{ width-columnSpacing - 55.0 }} {{ height / -2 + 0.25 }}"
```suggestion
               pos="{{ width-columnSpacing - 55f }} {{ height / -2 + 0.25 }}"
```

2024-11-09 10:37 UTC, snixtho commented on src/Modules/ScoreboardModule/Templates/Components/Header/HeaderContent.mt
> +        <frame id="header_content" pos="{{ width / 2.0 }} {{ height / -2.0 }}">
```suggestion
        <frame id="header_content" pos="{{ width / 2f }} {{ height / -2f }}">
```

2024-11-09 10:37 UTC, snixtho commented on src/Modules/ScoreboardModule/Templates/Components/Header/HeaderContent.mt
> +                   pos="{{ float.Parse(Theme.ScoreboardModule_Logo_Width, CultureInfo.InvariantCulture) * -0.5 - 4.0 }} 1.75"
```suggestion
                   pos="{{ float.Parse(Theme.ScoreboardModule_Logo_Width, CultureInfo.InvariantCulture) * -0.5 - 4f }} 1.75"
```

2024-11-09 10:37 UTC, snixtho commented on src/Modules/ScoreboardModule/Templates/Components/Header/HeaderContent.mt
> +                   size="{{ width/2.0-float.Parse(Theme.ScoreboardModule_Logo_Width, CultureInfo.InvariantCulture)-2.0 }} {{ height }}"
```suggestion
                   size="{{ width/2f-float.Parse(Theme.ScoreboardModule_Logo_Width, CultureInfo.InvariantCulture)-2f }} {{ height }}"
```

2024-11-09 10:37 UTC, snixtho commented on src/Modules/ScoreboardModule/Templates/Components/Header/HeaderContent.mt
> +                   pos="{{ float.Parse(Theme.ScoreboardModule_Logo_Width, CultureInfo.InvariantCulture) * -0.5 - 4.0 }} -1.75"
```suggestion
                   pos="{{ float.Parse(Theme.ScoreboardModule_Logo_Width, CultureInfo.InvariantCulture) * -0.5 - 4f }} -1.75"
```

2024-11-09 10:37 UTC, snixtho commented on src/Modules/ScoreboardModule/Templates/Components/Header/HeaderContent.mt
> +                   size="{{ width/2.0-float.Parse(Theme.ScoreboardModule_Logo_Width, CultureInfo.InvariantCulture)-2.0 }} {{ height }}"
```suggestion
                   size="{{ width/2f-float.Parse(Theme.ScoreboardModule_Logo_Width, CultureInfo.InvariantCulture)-2f }} {{ height }}"
```

2024-11-09 10:37 UTC, snixtho commented on src/Modules/ScoreboardModule/Templates/Components/Header/HeaderContent.mt
> +                   pos="{{ float.Parse(Theme.ScoreboardModule_Logo_Width, CultureInfo.InvariantCulture) * 0.5 + 4.0 }} 1.75"
```suggestion
                   pos="{{ float.Parse(Theme.ScoreboardModule_Logo_Width, CultureInfo.InvariantCulture) * 0.5 + 4f }} 1.75"
```

2024-11-09 10:37 UTC, snixtho commented on src/Modules/ScoreboardModule/Templates/Components/Header/HeaderContent.mt
> +                   size="{{ width/2.0-float.Parse(Theme.ScoreboardModule_Logo_Width, CultureInfo.InvariantCulture)-2.0 }} {{ height }}"
```suggestion
                   size="{{ width/2f-float.Parse(Theme.ScoreboardModule_Logo_Width, CultureInfo.InvariantCulture)-2f }} {{ height }}"
```

2024-11-09 10:37 UTC, snixtho commented on src/Modules/ScoreboardModule/Templates/Components/Header/HeaderContent.mt
> +                   pos="{{ float.Parse(Theme.ScoreboardModule_Logo_Width, CultureInfo.InvariantCulture) * 0.5 + 4.0 }} -1.75"
```suggestion
                   pos="{{ float.Parse(Theme.ScoreboardModule_Logo_Width, CultureInfo.InvariantCulture) * 0.5 + 4f }} -1.75"
```

2024-11-09 10:37 UTC, snixtho commented on src/Modules/ScoreboardModule/Templates/Components/Header/HeaderContent.mt
> +                   size="{{ width/2.0-float.Parse(Theme.ScoreboardModule_Logo_Width, CultureInfo.InvariantCulture)-2.0 }} {{ height }}"
```suggestion
                   size="{{ width/2f-float.Parse(Theme.ScoreboardModule_Logo_Width, CultureInfo.InvariantCulture)-2f }} {{ height }}"
```

2024-11-09 10:37 UTC, snixtho commented on src/Modules/ScoreboardModule/Templates/Components/Header/HeaderContent.mt
> +    <script once="true"><!--
Move script into its own file.

2024-11-09 10:37 UTC, snixtho commented on src/Modules/ScoreboardModule/Templates/Components/Row/Framemodel.mt
> +            <frame pos="{{ positionBoxWidth + columnSpacing }} {{ rowHeight / -2.0 }}" z-index="10">
```suggestion
            <frame pos="{{ positionBoxWidth + columnSpacing }} {{ rowHeight / -2f }}" z-index="10">
```

2024-11-09 10:37 UTC, snixtho commented on src/Modules/ScoreboardModule/Templates/Components/Row/Framemodel.mt
> +                <Flag height="{{ rowInnerHeight }}" />
Could this be a core component or is it specialized to the scoreboard only?

2024-11-09 10:37 UTC, snixtho commented on src/Modules/ScoreboardModule/Templates/Components/Row/Framemodel.mt
> +                           size="{{ rowInnerHeight * 2.0 }} {{ rowInnerHeight }}"
```suggestion
                           size="{{ rowInnerHeight * 2f }} {{ rowInnerHeight }}"
```

2024-11-09 10:37 UTC, snixtho commented on src/Modules/ScoreboardModule/Templates/Components/Row/Framemodel.mt
> +                           textsize="{{ Theme.UI_FontSize*2 }}"
```suggestion
                           textsize="{{ Theme.UI_FontSize*2f }}"
```

2024-11-09 10:37 UTC, snixtho commented on src/Modules/ScoreboardModule/Templates/Components/Row/Framemodel.mt
> +                       textsize="{{ Theme.UI_FontSize*2 }}"
Use the `text-xl` utility class instead and for the others too.

Ref:
- `text-xs`: `Theme.UI_FontSize*0.8`
- `text-normal`: `Theme.UI_FontSize` (or `text-primary` for default colors + normal size)
- `text-md`: `Theme.UI_FontSize*1.2`
- `text-lg`: `Theme.UI_FontSize*1.5`
- `text-xl`: `Theme.UI_FontSize*2`
- `text-2xl`: `Theme.UI_FontSize*4`
- `text-3xl`: `Theme.UI_FontSize*6`
- `text-4xl`: `Theme.UI_FontSize*8`

2024-11-09 10:37 UTC, snixtho commented on src/Modules/ScoreboardModule/Templates/Components/Row/Framemodel.mt
> +        <!--
move script into its own file

2024-11-09 10:37 UTC, snixtho commented on src/Modules/ScoreboardModule/Templates/Components/Row/PlayerActions.mt
> +                 textsize="{{ Theme.UI_FontSize*2 }}"
use `text-xl` class

2024-11-09 10:37 UTC, snixtho commented on src/Modules/ScoreboardModule/Templates/Components/Row/PositionBox.mt
> +                   textsize="{{ Theme.UI_FontSize*2 }}"
use `text-xl` class

2024-11-09 10:37 UTC, snixtho commented on src/Modules/ScoreboardModule/Templates/Scoreboard.mt
> +        <!--
move script into its own file

2025-02-05 20:06 UTC, araszka commented on src/Modules/ScoreboardModule/Templates/Components/Row/Framemodel.mt
> +                <Flag height="{{ rowInnerHeight }}" />
Could be made a core component. I'll keep it in mind when updating the scoreboard for teams mode.

2025-02-16 15:40 UTC, snixtho approved these changes

2025-02-16 15:44 UTC, merged